"""empty message

Revision ID: c5c46ad5ab9b
Revises: 4da03fd788c7
Create Date: 2024-02-18 21:25:51.459958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c46ad5ab9b'
down_revision = '4da03fd788c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
